language: python

services:
  - docker

python:
  - '3.7'

install:
  - sudo apt-get update -qq
  - pip install aiohttp
  - pip install requests
  - pip install pyflakes
  - pip install pytz
  - ./build.sh
script:
  - ADMIN_PASSWORD=admin
  - ROOT_DIR=${HOME}/buckets
  - SN_PORT=5101
  - HSDS_ENDPOINT=http://localhost:5101
  - BUCKET_NAME=hsds.test
  - echo "ROOT_DIR:" $ROOT_DIR
  - echo "HSDS_ENDPOINT:" $HSDS_ENDPOINT
  - mkdir $ROOT_DIR
  - mkdir ${HOME}/buckets/hsds.test
  - ./runall.sh
  - sleep 10
  - python testall.py