version: '2'
services:
  head:
    image: hdfgroup/hsds
    container_name: hsds_head
    restart: ${RESTART_POLICY}
    mem_limit: ${HEAD_RAM}
    environment:
      - TARGET_SN_COUNT=${SN_CORES}
      - TARGET_DN_COUNT=${DN_CORES}
      - NODE_TYPE=head_node
      - AWS_S3_GATEWAY=${AWS_S3_GATEWAY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${HEAD_PORT}:${HEAD_PORT}
    volumes:
      - ${PWD}/admin/config/:/config/

  dn:
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${DN_RAM}
    environment:
      - DN_HOST=${PUBLIC_DNS}
      - NODE_TYPE=dn
      - AWS_S3_GATEWAY=${AWS_S3_GATEWAY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${DN_PORT}
    depends_on:
      - head
    volumes:
      - ${PWD}/admin/config/:/config/

  sn:
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${SN_RAM}
    environment:
      - AWS_IAM_ROLE=${AWS_IAM_ROLE}
      - SN_PORT=${SN_PORT}
      - NODE_TYPE=sn
      - AWS_S3_GATEWAY=${AWS_S3_GATEWAY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DYNAMODB_GATEWAY=${AWS_DYNAMODB_GATEWAY}
      - AWS_REGION=${AWS_REGION}
      - AWS_LAMBDA_CHUNKREAD_FUNCTION=${AWS_LAMBDA_CHUNKREAD_FUNCTION}
      - AWS_LAMBDA_GATEWAY=${AWS_LAMBDA_GATEWAY}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - AZURE_APP_ID=${AZURE_APP_ID}
      - AZURE_RESOURCE_ID=${AZURE_RESOURCE_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_NAME=${SERVER_NAME}
      - AWS_DYNAMODB_USERS_TABLE=${AWS_DYNAMODB_USERS_TABLE}
      - VIRTUAL_HOST=${PUBLIC_DNS}
      - VIRTUAL_PORT=${SN_PORT}
      - HSDS_ENDPOINT=${HSDS_ENDPOINT}
      - SN_HOST=${PUBLIC_DNS}
      - GREETING=${GREETING}
      - ABOUT=${ABOUT}
    ports:
      - ${SN_PORT}:${SN_PORT}
    depends_on:
      - head
    volumes:
      - ${PWD}/admin/config/:/config/
